### ISSUE TITLE
Support JSON.stringify arguments

### ISSUE THREAD

**Issue by jaydenseric** [WebReflection/flatted#1]
It seems that [the only argument `flatted.stringify` has is `value`](https://github.com/WebReflection/flatted/blob/v0.2.3/index.js#L30).

How can you specify a formatted string, like with the third argument of `JSON.stringify`?

My use-case is to flatten an object with circular references for snapshot testing. For diffing, a formatted string is far better than all on one line. The current workaround:

```js
JSON.stringify(JSON.parse(flatted.stringify(foo)), null, 2)
```

**Comment by WebReflection** [comment]
It's written in the README:
https://github.com/WebReflection/flatted#why-not-circularjson-

If you need full JSON API support use [circular-json](https://github.com/WebReflection/circular-json/#circularjson)

**Comment by WebReflection** [comment]
FWIW the latest version supports 100% JSON API, including stringify arguments.
