### ISSUE TITLE
Are stringify and parse pure functions?

### ISSUE THREAD

**Issue by hadrien-toma** [WebReflection/flatted#12]
I would like to know if :
- `parse(data)` will return the same output when the same `data` input is provided
- `stringify(data)` will return the same output when the same `data` input is provided

**Comment by WebReflection** [comment]
Yes

**Comment by hadrien-toma** [comment]
Would you like me to add it in the documentation? :blush:

**Comment by WebReflection** [comment]
It's not needed. Flatted is a drop in JSON replacement so it's as pure as json by definition

**Comment by WebReflection** [comment]
JSON is pure by (recent) specs, and flatted uses JSON as is.

**Comment by hadrien-toma** [comment]
Alright, thank you very much! (After reading more, I am quite confuse and it seems the world I needed was effectively pure :sweat_smile:)

**Comment by WebReflection** [comment]
Your question is as simple as my answer: given same input it will always produce same output, as per specs.

If you mean the output should have ordered keys, I think you gave your own definition of pure, but I don't understand in any case what you're after or why, or what is your issue with JSON in general.

Nothing to do here anyway, take care.

**Comment by hadrien-toma** [comment]
Hum, you had perfectly answered. I simply added some information to explain my confusion searching a right mathematical word, "pure" or "indempotent"...

Such a weird replying message...

Anyway, let me thank you very much again!

**Comment by hadrien-toma** [comment]
Yes, I had already understood when you had said :
> JSON is pure by (recent) specs, and flatted uses JSON as is.

Thank you again again :wink: !

**Comment by WebReflection** [comment]
Look, given same object, sorted or not, the output is the same. This is by spec and for every engine, so your comment where you ask if you were wrong, the answer is yes, cause JSON is pure these days, it used not to be. No need to thank me, I just hope I've explained why you shouldn't care about purity here. If you need ordered keys, you can do it by your own before serialization.

**Comment by hadrien-toma** [comment]
Thanks for the precision about the engines. I realized I was wrong as soon as you made me aware that 
> JSON is pure by (recent) specs

:wink:
