### ISSUE TITLE
Performance Insights ⏰

### ISSUE THREAD

**Issue by shamasis** [WebReflection/flatted#14]
Thanks for this amazing module @WebReflection. ❤️ 

I was running some benchmark against CircularJSON and found Flatted to be tad slower. I wouldn't say my benchmarks were pure since they are running within my own project and not an independent benchmark.

~ https://github.com/postmanlabs/uvm/pull/262
```
Circular JSON:
no object communication x 3,274 ops/sec ±4.51% (34 runs sampled)
flat object communication x 3,458 ops/sec ±6.97% (22 runs sampled)
one level nested object communication x 3,543 ops/sec ±4.98% (19 runs sampled)
two levels nested object communication x 3,550 ops/sec ±7.71% (15 runs sampled)
full nested object communication x 3,764 ops/sec ±7.63% (13 runs sampled)
recursive nested object communication x 3,266 ops/sec ±7.60% (12 runs sampled)

Flatted:
no object communication x 3,389 ops/sec ±4.77% (34 runs sampled)
flat object communication x 3,017 ops/sec ±4.65% (25 runs sampled)
one level nested object communication x 2,998 ops/sec ±6.03% (22 runs sampled)
two levels nested object communication x 3,041 ops/sec ±4.61% (19 runs sampled)
full nested object communication x 3,176 ops/sec ±6.69% (13 runs sampled)
recursive nested object communication x 3,378 ops/sec ±4.74% (14 runs sampled)
```

I was wondering if you'd get some time to put your thoughts on this. :-)

**Comment by WebReflection** [comment]
Where is the source code size and complexity, hence maintainance ability, comparison?

**Comment by kunagpal** [comment]
@WebReflection The link was in the issue description: postmanlabs/uvm#262 😅

**Comment by WebReflection** [comment]
@kunagpal that doesn't answer my question. Flatted is few lines of code, less convolute, and basically perfect for what it does. It's also technically easier to implement in other programming languages, so the comparison is not fair.
There could be few manual optimizations to do but I don't think it's worth the time.
PRs demonstrating perf improvement welcome though, but I usually don't change what perfectly works, and it's battle tested, already.
