### ISSUE TITLE
Raw objects are reconstituted but not as the original object types?

### ISSUE THREAD

**Issue by roschler** [WebReflection/flatted#15]
I've noticed that when reconstituting a "flatted" JSON object created with the flatted `stringify` function, that the `parse` function does rebuild the object tree successfully, except that all the objects come back in "plain" object form, and not as the original objects types?  

For example, if you have an object such as:

```
function SomeObject() {
     // Some fields.
}
```
When loaded, you get a "plain" object with all the fields that `SomeObject` possessed, but it's not of type `SomeObject`, just `object` (in other words, the object has all the content, but would fail an **instanceof SomeObject** call. Is this the expected behavior, the loss of the original object type?

**Comment by WebReflection** [comment]
That's how JSON works, and flatted is JSON without circular references issue, nothing more, nothing less 👋

**Comment by roschler** [comment]
@WebReflection Thanks.  Do you know of a way to "cast" an object back to its original type, if you know what type of object it was supposed to be?  So if an object originally was a `SomeObject` type, is their a way to coerce it back to that kind of an object? (for example, associate the function vtables and other items of `SomeObject` with the data in a "primitive" object type that used to be a `SomeObject` object?).

**Comment by WebReflection** [comment]
The following is just one way to do that:
```js
window.nmsp = {
  Person: class Person {
    constructor(name = 'anonymous', age = 0) {
      this.name = name;
      this.age = age;
    }
    toJSON() {
      return Object.defineProperty(
        {
          name: this.name,
          age: this.age
        },
        "__proto__",
        {
          enumerable: true,
          value: "nmsp.Person"
        }
      );
    }
  }
};

const asJSON = JSON.stringify(new nmsp.Person);
// "{"name":"anonymous","age":0,"__proto__":"nmsp.Person"}"

const asPerson = JSON.parse(asJSON, (key, value) => {
  if (key === "") {
    const Class = value.__proto__
                        .split(".")
                        .reduce((ref, curr) => ref[curr], window);
    delete value.__proto__;
    Object.setPrototypeOf(value, Class.prototype);
  }
  return value;
});
// asPerson instanceof nmsp.Person;
```

You can use Flatted instead of JSON and it'll be the same 👋

**Comment by roschler** [comment]
Thanks again and thanks for writing/maintaining Flatted.
