### ISSUE TITLE
reviver must return original reference?

### ISSUE THREAD

**Issue by licstar** [WebReflection/flatted#16]
I'm trying to write a reviver to create my own class instances.
like this https://yuilibrary.com/yui/docs/json/json-freeze-thaw.html

However, if I return a new object, the reference will be changed.

```javascript
const a = [{}];
a[0].a = a;
a.push(a);

let s = Flatted.stringify(a);

let o1 = Flatted.parse(s);
console.log(o1[0].a === o1, o1); // true

let o2 = Flatted.parse(s, reviver);
console.log(o2[0].a === o2, o2) // false

function reviver(key, value) {
  if (value instanceof Array) {
    return value.slice(0);
  } else if (value instanceof Object) {
    return Object.assign({}, value);
  }
  return value;
}
```

**Comment by WebReflection** [comment]
> However, if I return a new object, the reference will be changed.

and where exactly is the surprise ? 🤔

**Comment by WebReflection** [comment]
Have you tried something like this instead ? It doesn't return new references every single time you encounter an Array or an Object.

```js
const wm = new WeakMap;
function reviver(key, value) {
  if (value instanceof Array) {
    return wm.get(value) || wm.set(value, value.slice(0)).get(value);
  } else if (value instanceof Object) {
    return wm.get(value) || wm.set(value, Object.assign({}, value)).get(value);
  }
  return value;
}
```

**Comment by WebReflection** [comment]
P.S. [Code Pen](https://codepen.io/WebReflection/pen/bZVgEb?editors=0011) that shows it works already 👋

**Comment by licstar** [comment]
> Have you tried something like this instead ? It doesn't return new references every single time you encounter an Array or an Object.
> 
> ```js
> const wm = new WeakMap;
> function reviver(key, value) {
>   if (value instanceof Array) {
>     return wm.get(value) || wm.set(value, value.slice(0)).get(value);
>   } else if (value instanceof Object) {
>     return wm.get(value) || wm.set(value, Object.assign({}, value)).get(value);
>   }
>   return value;
> }
> ```

great idea!
