### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by ndelangen** [WebReflection/flatted#2]
The docs are quite limited, would appreciate some more explanation how to use, and what for.

- When is this lib good to use?
- How does parse work
- document all params
- are [revivers](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse) supported
- can it also deal with dates, regex etc?

**Comment by ndelangen** [comment]
Thank you 🙇

**Comment by WebReflection** [comment]
> When is this lib good to use?

Whenever you want to forget about circular references in serialized objects and arrays

> How does parse work

The way you expect

> document all params

`flatted.stringify(any)` and `flatted.parse(string)`

> are revivers supported

it's written in the README: no

> can it also deal with dates, regex etc?

you can deal with JSON compatible data. Dates will show up as strings but regexp won't 'cause regexp aren't supported in JSON.
