### ISSUE TITLE
npm install in README

### ISSUE THREAD

**Issue by samsammurphy** [WebReflection/flatted#25]
It would be really helpful for attention and time deprived people like myself to have a oneliner on how to install in the README, e.g.

`npm install flatted/esm`

except ^ doesn't work

**Comment by samsammurphy** [comment]
I figured out it is

`npm install flatted`

**Comment by WebReflection** [comment]
Just to clarify, the `import` / `require` should work out of the box using `flatted`, those examples in the README are explicit for bundlers incapable of dealing with dual modules.

**Comment by alex-dixon** [comment]
Was just going to open an issue for this. Was looking to install from a package manager. May save some confusion to have package manager coordinates or install instructions in readme.
