### ISSUE TITLE
unable to import esm module

### ISSUE THREAD

**Issue by jkhsjdhjs** [WebReflection/flatted#26]
I'm unable to import `flatted/esm`, because the index file doesn't have the `.mjs` extension.

Error message:
```
(node:22685) ExperimentalWarning: The ESM module loader is experimental.
file:///home/jkhsjdhjs/git/flat/index.mjs:1
import {parse, stringify} from "flatted/esm";
        ^^^^^
SyntaxError: The requested module 'flatted/esm' does not provide an export named 'parse'
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:88:21)
```

Renaming `esm/index.js` to `esm/index.mjs` makes it work.

**Comment by WebReflection** [comment]
The extension .mjs is not needed.

**Comment by jkhsjdhjs** [comment]
I upgraded from `node v.11.15.0` to `node v12.8.1` and it still doesn't work.

#### index.mjs
```javascript
import {parse, stringify} from "flatted/esm";

const test = {
    test2: "test"
};

test.test = test;

console.log(stringify(test));
```
When I run `node --experimental-modules index.mjs` I get the following error:
```
internal/modules/esm/default_resolve.js:59
  let url = moduleWrapResolve(specifier, parentURL);
            ^

Error: Cannot find module '/home/jkhsjdhjs/git/flat/node_modules/flatted/esm' imported from /home/jkhsjdhjs/git/flat/index.mjs
    at Loader.resolve [as _resolve] (internal/modules/esm/default_resolve.js:59:13)
    at Loader.resolve (internal/modules/esm/loader.js:73:33)
    at Loader.getModuleJob (internal/modules/esm/loader.js:149:40)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:43:40)
    at link (internal/modules/esm/module_job.js:42:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```
(yes, I'm sure I actually installed the package)

According to the nodejs documentation the file either needs the `.mjs` extension or the `type: "module"` in the nearest `package.json`: https://nodejs.org/api/esm.html#esm_enabling

**Comment by WebReflection** [comment]
It's experimental for a reason, please use esm module to properly load ESM

**Comment by WebReflection** [comment]
https://www.npmjs.com/package/esm

**Comment by WebReflection** [comment]
Alternatively, just import from `flatted/cjs` to use the fallback

**Comment by jkhsjdhjs** [comment]
> It's experimental for a reason, please use esm module to properly load ESM

Ah ok, it would be cool if you could add that to the readme. Thanks!

**Comment by WebReflection** [comment]
I will 👋
