### ISSUE TITLE
Parser structure circular

### ISSUE THREAD

**Issue by ikkiphoenix** [WebReflection/flatted#28]
Hello, parse don't work.

i can strigify but when i parse it after i can't the exact structure circular and it's don't work

**Comment by WebReflection** [comment]
You do realize this module is downloaded 4 million times per week, right?

**Comment by ikkiphoenix** [comment]
I try to put in localStorage my variable socket. So i use flatted to the stringify and the parse.
Like you can see i don't have the original variable so i can't use the socket like i want.
flatted
![flatted](https://user-images.githubusercontent.com/10722788/64356245-31c93b80-d00b-11e9-8061-575d16238c59.PNG)


Thanks for help.

**Comment by WebReflection** [comment]
this serializes whatever can be serialized, like with JSON, except it supports circular dependencies, which has nothing to do with serializing sockets.

You need to understand how JSON works first, then you can use this in case you want to serialize **data that is serializable**, with circular dependencies.

**Comment by davalapar** [comment]
> 
> 
> I try to put in localStorage my variable socket. So i use flatted to the stringify and the parse.
> Like you can see i don't have the original variable so i can't use the socket like i want.
> flatted
> ![flatted](https://user-images.githubusercontent.com/10722788/64356245-31c93b80-d00b-11e9-8061-575d16238c59.PNG)
> 
> Thanks for help.

if my understanding is correct this module can only re-create basic types like objects & arrays and re-reference them circularly. sockets and custom classes, i think nah?

**Comment by WebReflection** [comment]
https://github.com/WebReflection/flatted/issues/28#issuecomment-528427797
