### ISSUE TITLE
Parse Method don't work like i want

### ISSUE THREAD

**Issue by ikkiphoenix** [WebReflection/flatted#29]
Hello again,

I try to put in localStorage my variable socket. So i use flatted to the stringify and the parse.
Like you can see i don't have the original variable so i can't use the socket like i want.
![flatted](https://user-images.githubusercontent.com/10722788/64356011-d5661c00-d00a-11e9-9894-5adad3ed4911.PNG)

Thanks for help.

**Comment by WebReflection** [comment]
https://github.com/WebReflection/flatted/issues/28#issuecomment-528427797

Please do not open another issue or you'll be blocked from this project.

Thank you.
