### ISSUE TITLE
Any isJSON method ?

### ISSUE THREAD

**Issue by stephaneeybert** [WebReflection/flatted#34]
How can we check for a variable being a JSON object ?

I get the error:
{message: Error: Uncaught (in promise): SyntaxError: Unexpected token e in JSON at position 0
on the variable:
eyJhbGciOiJIUzUxMiJ9.eyJlbWFpbCI6Im1pdHRpcHJvdmVuY2VAeWFob28uc2UiLCJzdWIiOiJtdXNpY25nIiwianRpIjoiYTdlMGJlNTUtZDUyZC00NjUyLTlmOGUtYWI4YzVlZDFmMTE4IiwiaXNzIjoiaHR0cDovL3RoYWxhc29mdC5jb20iLCJpYXQiOjE1ODI4ODE5NzYsImV4cCI6MTU4MzQ4Njc3Nn0.Dob7CvI3G5Gd8jzuEPKykKV3rHKeQwAr5YpCnVFH1l7kI-cHBR5xGskbPt37K_mvqU3cFicoQAnpPwH2iXnzYw
which is a refresh token.
I would like to check for the variable to be a valid JSON format before parsing it.

**Comment by stephaneeybert** [comment]
I could work around this with the following:

```
  private stringify(value: T): string {
    return stringify(value);
  }

  private parse(value: string): T | null {
    try {
      return parse(value);
    } catch (e) {
      return null;
    }
  }

```

**Comment by WebReflection** [comment]
This library does what native JSON does, and if native JSON throws, this library throws too.
