### ISSUE TITLE
'RangeError: Maximum call stack size exceeded' thrown when parsing large data set

### ISSUE THREAD

**Issue by mkramers** [WebReflection/flatted#39]
I am using `flatted` 3.0.4 to send/receive (potentially) circular JSON data to/from my API. For large JSON objects, I am experiencing the following error.

`(node:401691) UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded`

    at String.toString (<anonymous>)
    at /repo/node_modules/flatted/cjs/index.js:26:24
    at Array.reduce (<anonymous>)
    at revive (/repo/node_modules/flatted/cjs/index.js:22:59)
    at /repo/node_modules/flatted/cjs/index.js:29:43
    at Array.reduce (<anonymous>)
    at revive (/repo/node_modules/flatted/cjs/index.js:22:59)
    at /repo/node_modules/flatted/cjs/index.js:29:43
    at Array.reduce (<anonymous>)
    at revive (/repo/node_modules/flatted/cjs/index.js:22:59)`

My setup looks like this:
- Client generates JSON data which may be circular
- `flatted.stringify` is used in the client to send the flatted json data to the api
- the flatted data is stored in Postgres as JSONB

_some time later..._

- I retrieve the data from Postgres as a "regular (flatted)" json object
- I send it over the API when requested
- In the client, I call `parse(JSON.stringify(data))` which gives me back the data in its original JSON form

Generally, this works for me and the data is persevered. I realise that the docs it mentions not calling `parse(JSON.stringify(..))`, however I see no way around this, and it does work in general, however I suspect once it reaches a certain size it fails. I've created a project [here](https://github.com/mkramers/flatted-test/tree/master) demonstrating the issue with 2 different datasets (one that "works" and one that throws).

Let me know if I can provide any additional information.

Thanks,

**Comment by WebReflection** [comment]
> In the client, I call `parse(JSON.stringify(data))` which gives me back the data in its original JSON form

and why is that?

**Comment by mkramers** [comment]
@WebReflection I need a way to restore the "unflatted" object. Calling `parse(stringify(..))` returns a flatted JSON object when I use it in this context. Perhaps I am missing something here.

**Comment by WebReflection** [comment]
This works
```js
const fs = require('fs');
const {parse, stringify} = require('flatted');

['./65515.json', './65518.json'].forEach(fileName => {
  let dataString = fs.readFileSync(fileName).toString('utf-8');
  let rawJson = JSON.parse(dataString);
  let {toolData} = rawJson;

  let stringified = parse(JSON.stringify(toolData.slice(0, 8970)));

  console.log(stringified);
});
```

**Comment by WebReflection** [comment]
as soon as I have `toolData.slice(0, 8971)` it breaks ... so I suggest you check why is that, and if you have any clue, I'd be happy to have a look 👍

**Comment by WebReflection** [comment]
actually, I think it's the call-tail optimization failing here ... on it

**Comment by mkramers** [comment]
Thanks @WebReflection - as a side-note, it fails at `7853` for me (which is obviously indicative of our different systems' call stack size). Thanks for looking into this!

**Comment by WebReflection** [comment]
so there's an `origin no-tail` master pre-built that might solve this issue ... but I don't want to rush any change in here, please try it out, if possible

**Comment by mkramers** [comment]
@WebReflection - this fix seems to work on both my test case as well as in my API. Thanks so much for the quick responses.

**Comment by WebReflection** [comment]
the MR is here https://github.com/WebReflection/flatted/pull/40

my only concern, for such widely adopted module, is to go patch, or go major ... I might dare patch, as code coverage suggests everything is fine, and your test case passes too!

**Comment by WebReflection** [comment]
maybe *minor* is a good compromise after all

**Comment by WebReflection** [comment]
it's up

**Comment by GEORGE-GICHURU** [comment]
Error: Unexpected token < in JSON at position 0

solution?
