### ISSUE TITLE
does not seem to work with hermes runtime (react-native)

### ISSUE THREAD

**Issue by matgardon** [WebReflection/flatted#46]
when importing { parse }, it is undefined in hermes, while available and functioning normally in tests running on node / V8.
I don't see obvious incompatibilities with `Map, Set, Object.keys, Array.prototype.reduce` in [hermes](https://hermesengine.dev/docs/language-features), but this is probably linked.

**Comment by WebReflection** [comment]
I don't have much details here:
  * what is the error?
  * where is the code example and the command to start hermes?

... and so on and so fort ...

**Comment by WebReflection** [comment]
anyway, just tested with hermes 0.7 this:

```js

const o = {};
o.a = [o];
print(parse(stringify(o)));
```

it works without issues. If you have issues in requiring or importing it though, you'll have more luck filing a bug in hermes, as this module works everywhere and follows NodeJS and npm standard to define exports.

**Comment by matgardon** [comment]
fair enough, thanks for the quick reply. I'm investigating it on hermes / react-native side, possibly a problem with the import / export context used, although I don't get why this works for other modules and not this one, still quite puzzled. I'll try to get a good answer and report here in case anyone else stumbles upon the same issue.

**Comment by matgardon** [comment]
BTW circularJSON works without issue too (so I'm staying on it as long as I don't find a solution).

**Comment by WebReflection** [comment]
@matgardon the difference is that this is dual module, accordingly with NodeJS standard, and backward compatible with NodeJS < 14, rollup, Babel, and TS ... so the difference is [in the package](https://github.com/WebReflection/flatted/blob/master/package.json), which is different from the [circular json one](https://github.com/WebReflection/circular-json/blob/master/package.json), but this is a Hermes issue in resolving packages, as the code here works without issues whatsoever in Hermes too.

**Comment by WebReflection** [comment]
@matgardon would you mind checking if using this in flatted package.json works?

```js
  "exports": {
    ".": {
      "import": "./esm/index.js",
      "default": "./cjs/index.js"
    },
    "./package.json": "./package.json"
  },
```

If it does, I don't mind switching to this export, thanks.
