### ISSUE TITLE
What's the performance compare to JSON.stringify?

### ISSUE THREAD

**Issue by samuelcastro** [WebReflection/flatted#47]
Do you have any benchmark comparing JSON and Flatted?

Thank you.

**Comment by WebReflection** [comment]
Flatted uses a parser and revival function, so it's same JSON performance + that overhead, not much to compare, except Flatted can produce smaller outcome (strings are unique) and doesn't break with recursion.

**Comment by WebReflection** [comment]
P.S. I guess the bottom line is that: it doesn't matter, if you use Flatted is because you need to solve recursions, not because you want to be faster than JSON.
