### ISSUE TITLE
Extract PHP implementation to separate (Composer) package

### ISSUE THREAD

**Issue by mbrodala** [WebReflection/flatted#48]
This package brings a PHP implementation which is very unexpected from a Node/NPM package.

For a clear separation I suggest to extract the PHP implementation to a separate package/repository and publish it via Packagist.

**Comment by WebReflection** [comment]
What issue is this causing? The idea is that one can use `npm` to install `flatted` and then use that path to `include_once` the PHP helper too. More are coming (Python, etc), and I prefer to keep all of them in one place, instead of having various repositories to report a bug that would affect all of them, if any, ever.

**Comment by mbrodala** [comment]
The "issue" I saw is that PHP CS Fixer reported changes on this file, so that wouldn't be a big deal.

At first I thought that a backdoor was installed only to discover that it was only a PHP implementation.

In any case it is very unlikely that one will use the PHP implementation like this. Nowadays Composer/Packagist are standard for any PHP code so you will need to set up a package for this sooner or later. I assume the same holds true for Python/PIP.

Also there are strategies to keep reports/changes in one place:

1. Set up a monorepo project with subtree splits for the specific packages (see Symfony)
2. Set up multiple projects but disallow reporting issues in these; instead set up an additional (template) project for issue reporting only. (see API Platform)

**Comment by WebReflection** [comment]
So, I have very limited time for this, which doesn’t look like an issue. The file in npm could be curled via cdn too. Last time someone complained about not having a mono repo I’ve spent hours to put it all together and received **zero** contributions from that time on, as nobody had a clue how to file issues or provide PRs.

I might think about packaging properly in PHP, but I had zero requests about it.

This one looks like a non issue too … this package is downloaded 70M times per month, and this is the first time I have a complain. Also, backdoors in PHP are not really a thing, are they? I would agree if it was a binary or executable or something, but it’s just open source and my npm is behind 2FA too.

so …. what are we trying to solve here? 🤔

**Comment by mbrodala** [comment]
It's not a big deal as mentioned, it just startled me. If you don't see anything that needs to be done here you are free to leave it at that. :-)

I'll close this one.

**Comment by robopzet** [comment]
Just want to let you know it also surprised me that a search in my IDE came up with a PHP file in `node_modules`. That seems suspect so I had to investigate.

Agree with @mbrodala that developers using PHP expect PHP packages on Packagist, not npm. If you want to get people to use it I think it's better to publish it there.

**Comment by WebReflection** [comment]
My situation hasn’t changed though … my comment remains:
https://github.com/WebReflection/flatted/issues/48#issuecomment-875735747

**Comment by PieterJanVdb** [comment]
Having a PHP file in your node_modules folder can cause buildpack detectors to unexpectedly conclude that the project being built is a PHP one. I just ran into this particularly annoying issue. As this is part of eslint, I can imagine multiple people that use the GoogleCloud Buildpacks to run into this exact same issue if they don't manually specify the preferred runtime.

**Comment by WebReflection** [comment]
No tool should ever have issues here ... and the path is defined by the
package.json.

Change or update your tools if you have issues with any non JS file within
a JS module/package.
