### ISSUE TITLE
Module '"flatted"' has no exported member 'toJSON'.ts(2305)

### ISSUE THREAD

**Issue by marcomow** [WebReflection/flatted#49]
toJSON and fromJSON are not available

installed using `yarn add flatted` and added version v1.22.10

**Comment by WebReflection** [comment]
https://github.com/WebReflection/flatted/blob/main/esm/index.js#L93-L94 and we are version 3.2.1 here, not sure how to help.

**Comment by mattamusprime** [comment]
I have the same issue.  I installed with npm, and if I try to import toJSON, my IDE complains.  I'm using version 3.2.1.

I believe it's because https://github.com/WebReflection/flatted/blob/main/types.d.ts needs to have all the methods instead of just stringify and parse.

**Comment by WebReflection** [comment]
OK then, but as I don't use TS, PR welcome, thanks 👍

**Comment by mattamusprime** [comment]
Sure, I made a PR, see here: #50

**Comment by WebReflection** [comment]
It's up and running. Thank you!
