### ISSUE TITLE
Incorrect output stringify with space parameter  (v3.2.2)

### ISSUE THREAD

**Issue by ShiJuuRoku** [WebReflection/flatted#51]
**Object to stringify**

`
const httpErrorResponse = {
  status: 400,
  statusText: 'Bad Request',
  ok: false,
  name: 'HttpErrorResponse',
  error: {
    type: 'https://tools.ietf.org/html/rfc7231#section-6.5.1',
    title: 'One or more validation errors occurred.',
    status: 400,
    traceId: '00-8fc9dd440756cb499bcfe4a64c4a1d0b-a2ea5b0d7432b445-00'
  },
  httpErrorResponse: {}
};
`

Result with `JSON.stringify(httpErrorResponse, null, 2)` :

![image](https://user-images.githubusercontent.com/3122358/131007972-27d5d261-b85c-45d9-b225-17f4bfe4e701.png)

Result with `flatted.stringify(httpErrorResponse, null, 2)` :

![image](https://user-images.githubusercontent.com/3122358/131008105-5f94b271-f410-424c-97f2-46aa238449b7.png)

**Comment by WebReflection** [comment]
[expected](https://github.com/WebReflection/flatted#flatted-vs-json) ... you can't parse Flatted output with JSON.
