### ISSUE TITLE
Reviver not updating references

### ISSUE THREAD

**Issue by nux17** [WebReflection/flatted#52]
I am working with a pretty big model with circular references being transfered from a WebWorker.
As this modal wasn't JSON serializable, I'm using flatted which works wonders.

I am yet to manage how to fully restore my custom objects using the `revive` function.

It seems that all "root" objects are being correctly recasted as their original class types, but I am losing the original class types in some nested references.

My revival function : 

```
const model = parse(data, (key, val) => {
                            if (val !== null && val.className && val.className in models) {
                                if (val.className === "DataProvider") {
                                    return new DataProvider(val.providerData)
                                }
                                return Object.assign(new (<any>models)[val.className](), val)
                            }
                            return val;
                        })
```

Uses reflection from a className added with the replacer function for custom object types.

Here we can see that classes have been restored : 
![image](https://user-images.githubusercontent.com/6410827/143066620-81d0e534-35db-4273-958e-420764985fd7.png)

But deeper in some objects that are references are only referenced as basic `Object` : 

![image](https://user-images.githubusercontent.com/6410827/143066989-c5f031cf-6b94-4e53-8c40-8e90944bf22b.png)

Any idea how I could keep the types consistent throughout all my model?

Thank you.

**Comment by nux17** [comment]
I think I would need a way to ensure that indexed values referencing objects points to the "final form" of the pointed object after being casted.

**Comment by WebReflection** [comment]
I think I need an example that fails to work on ... as code coverage around the revival is green, and I have no idea, nor data, to reproduce your issue, sorry 🤷

**Comment by WebReflection** [comment]
P.S. to me it looks like you'd be better off with a `WeakMap` or a `Map` you can clean after revival ...

```js
if (val !== null && val.className && val.className in models) {
  if (map.has(val))
    return val;
  // the rest of your code so you return the same instance
  // when val is found ... remember to
  map.set(val, instance);
  return instance; // though, or bye bye reference
}
```

**Comment by WebReflection** [comment]
Moreover: be sure you don't parse over and over the same stuff ... because if you assign properties, next time those properties will be re-assigned again over and over ... nothing to fix here, for what I can tell.

Happy to re-open once you have something I can work on, thank you 👋

**Comment by nux17** [comment]
I am trying to make a working example on CodeSandbox. I'll try your solution.
It seems that `val` is an index when concerning a referenced object, hence the first condition isn't met.
Maybe I could try to map those values to corresponding objects.

Thanks for helping!

**Comment by WebReflection** [comment]
my thinking is that your issue, if it's caused by what you think is caused, should be small enough to reproduce as code in here. The CodeSandbox works too though, as long as I manage to understand, and debug, what's going on, thanks!

**Comment by WebReflection** [comment]
I am trying this and it seem to work?

```js
import { parse, stringify } from "flatted";
import * as models from "./models";

const b = new models.B();
const a = b.a;
a.setB(b);

const obj = {
  a: a
};

const str = stringify(obj);
console.log(str);

const mapped = new Map;
const ret = parse(str, (k, v) => {
  console.log(k, v);
  if ((<any>models)[v.className]) {
    if (!mapped.has(v))
      mapped.set(v, Object.assign(new (<any>models)[v.className](), v));
    return mapped.get(v);
  }
  return v;
});
console.log(ret);
```

There are at least 2 things that could be improved:

  1. use console.assert or provide evidence about what is not working in that demo.
  2. understand that the revival is not responsible for you replacing instances ... that's native JSON behavior, you should take care of **not** doing that, or better, when the same instance has been received, and there was a replacement, **you** should return such replacement, **or** feel free to return new instances each time.

Thoughts?

**Comment by nux17** [comment]
It seems that now we are losing the object after the first depth level.
I've added asserts to the CodeSandbox.

Agreed with point 2, but unsure on how to properly achieve that.

**Comment by WebReflection** [comment]
So, the situation is like this one:
```
[{"a":"1"},{"className":"2","b":"3"},"A",{"className":"4","a":"1"},"B"]

 {"a":"1"}
      {"className":"2","b":"3"} ◁━━━━━━━━━━━━━━━━━━━┓
                   "A"     {"className":"4","a":"1"}┃
                                        "B"      ┗━━┛
```
The moment you transform the first object into an instance, it's inner `b` property points at the raw object that hasn't been transformed yet, and that's expected, or better, that's exactly how `JSON.parse(str, reviver)` works.

```js
JSON.parse(
  '[{"a":"1"},{"className":"2","b":"3"},"A",{"className":"4","a":"1"},"B"]',
  (k, v) => {
    if (typeof v === 'object' && v)
      console.log(k, v);
    return v;
  }
);
```

This produces the following output, which represent the objects A, B, and A (without transformations/recursion):

```
{a: '1'}
{className: '2', b: '3'}
{className: '4', a: '1'}
```

If you change `JSON` with `Flatted`, the outcome is exactly the same: A, B, and A.

When you create A, you don't create B, you just attach whatever `b` points at, as copy, so that the second time A is passed along, you know the instance, but you've no idea about its properties.

## Solution

Instead of going through recursion within recursion, I suggest you **upgrade** instances, instead of replacing these:

```js
const {setPrototypeOf} = Reflect;
const updated = new Set;
const ret = parse(str, (_, v) => {
  if (
    v &&
    typeof v === 'object' &&
    'className' in v &&
    !updated.has(v)
  ) {
    updated.add(v);
    setPrototypeOf(v, models[v.className].prototype);
  }
  return v;
});
```

This is because if your instances are defined by fields you can just assign, there's no reason to shadow these in the first place.
Above code passes the test indeed without issues, because whenever references are found and upgraded, whoever owns those references will have these upgraded too without needing to re-assign, and re-contrcut, everything.

**Alternatively** you need to recursively check all entries you are going to assign and preemptively create instances through references so that you can return these later on.

The problem is simple: flatted works left to right, but you can have recursion defined right to left, so that when you replace left, right things won't be reflected in there.

**Comment by nux17** [comment]
Thank you for your answer,

This looks a lot like the answer to the question I asked on StackOverflow : https://stackoverflow.com/questions/70020846/keeping-nested-prototype-methods-from-object-transfering-from-webworker/

And this actually works.

Thank you again for helping, problem solved.

**Comment by WebReflection** [comment]
@nux17 I really **don't** like the fact you never mentioned to me there was a StackOverflow issue around this ... now somebody else with a solution that is not efficient at all and use `setPrototypeOf` more than it shuold took 100 points and I keep being confined as the one with the best solution and zero reward out there ... pretty sad, to be honest.

I'll write again the solution there, feel free to change your mind about which answer is better.
