### ISSUE TITLE
Problem in serialization of javascript Date()

### ISSUE THREAD

**Issue by ggreco** [WebReflection/flatted#56]
If I try to serialize an object tree that contains also some date objects (created with new Date() ) in the output I get the date converted to a string, and to fix it I should iterate the elements and do something like element.date = new Date(element.date).

Here is a minimal example to reproduce the problem:

```typescript
import {parse, stringify} from 'flatted';

class Obj {
    name: string;
    date: Date;
}

const original: Obj[] = [
    { name: "test1", date: new Date(10000000) },
    { name: "test2", date: new Date(10000000) },
];

const flattened = stringify(original);
const final = parse(flattened);

console.log("Original", original);
console.log("Final", final);
```

This is the output:
<img width="536" alt="image" src="https://user-images.githubusercontent.com/1829939/162189489-962aea29-3210-48e5-83a1-2bfac8151f9d.png">

... as you can see the dates are strings in the output.

**Comment by WebReflection** [comment]
This is how JSON works, it has nothing to do with this module. You need [a reviver](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse#parameters) callback.
