### ISSUE TITLE
Using it with BSON

### ISSUE THREAD

**Issue by deakjahn** [WebReflection/flatted#64]
Before I start to work on it: do you know of any attempt to use Flatted with BSON? I'd need to store to binary but all my data have circular references. Yours being a reviver-replacer could make coupling the two possible.

The naive approach of

    bson.serialize(json.stringify(clone.serialize(data, { json: true, lossy: true })))

doesn't work. Well, it does, sort of, but turns a 300k JSON into 4 megabytes, so not exactly. :-)

Come to think of it, the format of Structured Clone seems even better suited to binary saving.

**Comment by WebReflection** [comment]
[this module](https://github.com/ungap/structured-clone) already give you a way to serialize and deserialize in a structured clone fashion:

```js
import {serialize, deserialize} from '@ungap/structured-clone';

const serialized = serialize(data, { json: true });
```

**Comment by WebReflection** [comment]
closing as there won't be any action for me, feel free to ask more though, if needed 👋

**Comment by deakjahn** [comment]
Yes, that's what I mentioned in the last sentence. The size gain is not as large as I expected, though. I simply save to BSON directly your first step, without turning it into a string:

    bson.serialize(clone.serialize(this, { json: true, lossy: true }))

**Comment by WebReflection** [comment]
I am not sure I am following ... but if you have a lot of recursion for very small objects I wouldn't expect size gain although nowhere in my projects (flatted / structured-clone) I claim or mention any size gain ... ?

**Comment by WebReflection** [comment]
P.S. if you use `json: true` *lossy* becomes implicit

**Comment by deakjahn** [comment]
Certainly not. I need to use BSON instead of JSON for the size gain, your module has nothing to do with it. :-) Yours is really needed because my data is by definition circular, it's a tree where all nodes refer back to other nodes. But anyway, the resulting BSON can be compressed quite well so I'll be probably fine.
