### ISSUE TITLE
Hi WebReflection! 🌈 🦄 Why no undefined support? :O 

### ISSUE THREAD

**Issue by lopugit** [WebReflection/flatted#68]
I noticed that within an array, undefined is transformed to null, but on an object property, it is simply ignored :O 

I'm guessing there's a reason behind this? 

Cheers! 

Love your work to the moon and back 🚀🌛

**Comment by lopugit** [comment]
Ah I see that JSON stringify/parse does not support undefined !

Thanks!!! :) 

Would still be nice if it was set to null instead of undefined though! ❤️

**Comment by WebReflection** [comment]
Flatted does what JSON does

**Comment by WebReflection** [comment]
If you want more types or behavior use standards that support that such as structured clone (mentioned in the README of this project).

flatted will never diverge from json, it’s rock solid stable and battle tested and intend to keep it that way without any surprise whatsoever.

**Comment by lopugit** [comment]
No worries Andrea! Makes total sense, thank you so much! :)
