### ISSUE TITLE
flatted.php line 23 `$this->value = $value;` is deprecated.

### ISSUE THREAD

**Issue by MasaruKitajima** [WebReflection/flatted#69]
I'm running PHP 8.2.

When I open `flatted.php` with VisualStudio Code, or open test.php on the browser, I got 

> PHP Deprecated:  Creation of dynamic property FlattedString::$value is deprecated in  flatted.php on line 23

Please update.

**Comment by WebReflection** [comment]
It's up and running without deprecation warnings.

**Comment by MasaruKitajima** [comment]
@WebReflection ,
Thank you for quick fix.
It works very well.
Thanks again!
