### ISSUE TITLE
`TypeError: $ is not a function`

### ISSUE THREAD

**Issue by juliankrispel** [WebReflection/flatted#8]
Getting this on a fresh install, in a simple create react app

![image](https://user-images.githubusercontent.com/1188186/46538023-bf0b8980-c8aa-11e8-9796-0c8cd8aa44b3.png)

**Comment by juliankrispel** [comment]
oh nvmd, misunderstood the api

**Comment by juliankrispel** [comment]
actually, this still should work I'm using stringify just like this `stringify({a: 1})`

**Comment by juliankrispel** [comment]
false alarm 😅

**Comment by WebReflection** [comment]
1. the API is the JSON one
2. before thinking there is a bug here, please be sure JSON would work beside a recursion error

Thanks
