### ISSUE TITLE
In the zip released by mistake the cache was not cleaned, so there is an old bytecode-compiled in __pychache__

### ISSUE THREAD

**Issue by ZedToldus** [WebReflection/flatted#81]
In the zip released by mistake the cache was not cleaned, so there is an old bytecode-compiled in __pychache__
package\python\__pycache__\flatted.cpython-311.pyc
which is reported as an issue by Team Reviewer
The zip is https://registry.npmjs.org/flatted/-/flatted-3.3.1.tgz
To see the bytecode just extract the zip.

**Comment by WebReflection** [comment]
@ZedToldus now I understand and I've published a version without that `__pycache__` around ... I also pushed for the next time a better package.json with explicit files to include, as opposite of remembering what to exclude in `.npmignore` ... we should be good.
